- name: Add PostgreSQL GPG key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  tags: [postgresql_install]

- name: Add PostgreSQL repository
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: yes
  tags: [postgresql_install]

- name: Install PostgreSQL packages
  apt:
    name: "{{ postgresql_packages }}"
    state: present
    update_cache: yes
  tags: [postgresql_install]

- name: Ensure PostgreSQL service is enabled
  service:
    name: "{{ postgresql_service_name }}"
    enabled: yes
  tags: [postgresql_install]
