{
 "title": "NATS Server Dashboard",
 "description": "NATS Server Dashboard for use with built-in Prometheus NATS Exporter into nats official helm charts",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "nats_varz_cpu", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Server Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "nats_varz_mem", "legendFormat": "{{server_id}}" }
   ]
  },
  { "title": "Throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Bytes In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "nats_varz_in_bytes", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "NATS Msgs In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nats_varz_in_msgs", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "nats_varz_out_bytes", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "NATS Msgs Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nats_varz_out_msgs", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "rate(Bytes In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_varz_in_bytes[1m]))"
    }
   ]
  },
  {
   "title": "rate(NATS Msgs In)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_varz_in_msgs[1m]))"
    }
   ]
  },
  {
   "title": "rate(Bytes Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_varz_out_bytes[1m]))"
    }
   ]
  },
  {
   "title": "rate(NATS Msgs Out)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nats_varz_out_msgs[1m]))"
    }
   ]
  },
  { "title": "Client Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nats_varz_connections", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nats_varz_subscriptions", "legendFormat": "{{server_id}}" }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nats_varz_slow_consumers", "legendFormat": "{{server_id}}" }
   ]
  }
 ]
}