- name: Install PostgreSQL client
  apt:
    name: postgresql-client
    state: present
    update_cache: yes

- name: Ensure backup directory exists
  file:
    path: /var/backups/postgresql
    state: directory
    owner: postgres
    group: postgres
    mode: '0700'

- name: Copy backup script
  template:
    src: backup.sh.j2
    dest: /usr/local/bin/postgres_backup.sh
    owner: postgres
    group: postgres
    mode: '0755'

- name: Setup cron job for PostgreSQL backup
  cron:
    name: "PostgreSQL daily backup"
    user: postgres
    minute: "0"
    hour: "2"
    job: "/usr/local/bin/postgres_backup.sh"
