name: Deploy Infrastructure

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Run Ansible playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
          SUDO_PASS: ${{ secrets.SUDO_PASSWORD }}
        run: |
          ansible -i inventory.yml all -m raw -a "apt-get update" --become --extra-vars "ansible_become_password=$SUDO_PASS"
          ansible-playbook -i inventory.yml playbook.yml --extra-vars "ansible_become_password=$SUDO_PASS"